apiVersion: v1
kind: Service
metadata:
  name: grafana-llm-nlp-svc
  namespace: mcp
spec:
  selector:
    app: grafana-llm-nlp
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30036
